# Generated by Django 5.2.7 on 2025-10-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_booking_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingItem',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
